### ISSUE TITLE
m4 1.4.20 release breaking Alien::m4 for older distributions.

### ISSUE THREAD

**Issue by chargr** [PerlAlien/Alien-m4#22]
The release of m4 on 2025-05-10 breaks the build for older gcc versions

perl 5.32.1

https://ftp.gnu.org/gnu/m4/

using centos6 gcc
```
[root@5e6828a608ad tmp]# gcc -dumpversion
4.4.7
```

```
Alien::Build::Plugin::Core::Download> decoding html
Alien::Build::Plugin::Core::Download> candidate *https://ftp.gnu.org/gnu/m4/m4-1.4.20.tar.gz
Alien::Build::Plugin::Core::Download> candidate  https://ftp.gnu.org/gnu/m4/m4-1.4.20.tar.gz.sig
Alien::Build::Plugin::Core::Download> candidate  https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.gz
Alien::Build::Plugin::Core::Download> candidate  https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.gz.sig
Alien::Build::Plugin::Core::Download> candidate  https://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.gz
Alien::Build::Plugin::Core::Download> candidate  https://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.gz.sig
Alien::Build::Plugin::Core::Download> candidate  https://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz
Alien::Build::Plugin::Core::Download> candidate  https://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz.sig
Alien::Build::Plugin::Core::Download> candidate  ...
Alien::Build::Plugin::Core::Download> setting version based on archive to 1.4.20
Alien::Build::Plugin::Core::Download> downloaded m4-1.4.20.tar.gz
```

```
format.c: In function 'expand_format':
format.c:355: error: #pragma GCC diagnostic not allowed inside functions
format.c:356: error: #pragma GCC diagnostic not allowed inside functions
format.c:385: error: #pragma GCC diagnostic not allowed inside functions
make[3]: *** [format.o] Error 1
make[3]: Leaving directory `/scripts/.cpanm/work/1747171539.123/Alien-m4-0.21/_alien/build_S75V/m4-1.4.20/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/scripts/.cpanm/work/1747171539.123/Alien-m4-0.21/_alien/build_S75V/m4-1.4.20'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/scripts/.cpanm/work/1747171539.123/Alien-m4-0.21/_alien/build_S75V/m4-1.4.20'
external command failed at /carton/perl5.local/lib/perl5/Alien/Build/CommandSequence.pm line 88.
make: *** [_alien/mm/build] Error 2
-> FAIL Installing Alien::m4 failed. See /scripts/.cpanm/work/1747171539.123/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Alien::m4' is not installed
-> FAIL Bailing out the installation for Alien-GMP-1.16.
-> FAIL Installing the dependencies failed: Module 'Alien::GMP' is not installed
-> FAIL Bailing out the installation for Math-GMP-2.25.
-> FAIL Installing the dependencies failed: Module 'Math::GMP' is not installed
-> FAIL Bailing out the installation for /carton/.
```

**Comment by chargr** [comment]
Interestingly compiles with gcc 4.1.2 on centos5.

/shrug

**Comment by chargr** [comment]
setting `PATH=/path/to/m4/bin:$PATH` works but setting `M4=/path/to/m4/bin/m4` does not.  
i had only tried setting M4 earlier.

I realize now, M4 variable is tried last, so the older unqualified m4 is found first in default path.

so workaround is to use locally installed m4 that qualifies via $PATH

(also this compiles on centos5 with gcc 4.1.2)
